package wk.emailbutler;
// Generated by the WOLips Templateengine Plug-in at Apr 15, 2007 12:30:55 PM


import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WODirectAction;
import com.webobjects.appserver.WORequest;

public class DirectAction extends WODirectAction {

    public DirectAction(WORequest aRequest) {
        super(aRequest);
    }

    public WOActionResults defaultAction() {
        return pageWithName(Main.class.getName());
    }
}