package wk.emailbutler;
// Generated by the WOLips Templateengine Plug-in at Apr 15, 2007 12:30:55 PM

import er.extensions.appserver.ERXSession;

public class Session extends ERXSession {
	public Session() {
	}
}