package wk.emailbutler;
// Generated by the WOLips Templateengine Plug-in at Apr 15, 2007 12:30:55 PM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class Main extends WOComponent {

    public Main(WOContext context) {
        super(context);
    }

}